version: '3'

services:
  #mongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  #Node API service
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    container_name: web
#    environment:
#      PORT: 3000

  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web
      - mongo_db


volumes:
  mongo_db: {}

