version: '3'

services:
  #mongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    env_file:
#      - $env
#    environment:
#        MONGO_INITDB_ROOT_USERNAME: $user
#        MONGO_INITDB_ROOT_PASSWORD: $pass

  #Node API service
  api:
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URI: "${DATABASE_URI}"
      DB_NAME: my_db
      NAME:
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}